POST http://localhost:3001/api/managerSessions HTTP/1.1
content-type: application/json

{
    "username": "manager1@ezwh.com",
    "password":"testpassword"
}

###
GET http://localhost:3001/api/skus HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/api/skus/3 HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/sku HTTP/1.1
content-type: application/json

 {
        "description" : "ciao",
        "weight" : 100,
        "volume" : 50,
        "notes" : "second SKU",
        "price" : 13.99,
        "availableQuantity" : 2
    }

###

PUT http://localhost:3001/api/sku/1 HTTP/1.1
content-type: application/json

{
    "newDescription" : "a new sku",
    "newWeight" : 100,
    "newVolume" : 50,
    "newNotes" : "first SKU",
    "newPrice" : 10.99,
    "newAvailableQuantity" : 100
}

###
PUT http://localhost:3001/api/sku/1/position HTTP/1.1
content-type: application/json

{
    "position": "500224542413"
}
###
DELETE http://localhost:3001/api/skus/1 HTTP/1.1
content-type: application/json



