POST http://localhost:3001/api/managerSessions HTTP/1.1
content-type: application/json

{
    "username": "manager1@ezwh.com",
    "password":"testpassword"
}

###
GET http://localhost:3001/api/userinfo HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/api/suppliers HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/api/users HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/newUser HTTP/1.1
content-type: application/json

{
        "username":"user2@ezwh.com",
        "name":"John",
        "surname" : "Smith",
        "password" : "testpassword",
        "type" : "customer"

    }

###
POST http://localhost:3001/api/managerSessions HTTP/1.1
content-type: application/json

{
    "username": "manager1@ezwh.com",
    "password":"testpassword"
}

###
POST http://localhost:3001/api/customerSessions HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/supplierSessions HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/clerkSessions HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/qualityEmployeeSessions HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/deliveryEmployeeSessions HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/logout HTTP/1.1
content-type: application/json

###
PUT http://localhost:3001/api/users/user2@ezwh.com HTTP/1.1
content-type: application/json

{
        "oldType" : "customer",
        "newType" : "clerk"
    }

###
DELETE http://localhost:3001/api/users/user2@ezwh.com/clerk HTTP/1.1
content-type: application/json

###